### ISSUE TITLE
Error when starting server

### ISSUE THREAD

**Issue by ndo360** [spamguy/diplomacy#38]
Salutations! I have seemed to hit a roadblock. I keep getting this error when attempting to run the server:

C:\Users\17clinen\Desktop\diplomacy-master\server>node server.js
info: Express server listening on 9000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.
1:6379
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

Do you know if i'm missing a dependancy or something? Would like to get this up and running.
-Thanks
Noah

**Comment by spamguy** [comment]
Hello there!

This project is no longer supported, at least not in this form. You can visit [the active dipl.io repository](https://github.com/spamguy/dipl.io) and run that. You'll find it infinitely easier to set up, too, because there are far fewer dependencies. If you have any trouble there I'll be glad to work through it and improve documentation.

FWIW: The error above is caused by not having Redis installed or set up correctly. It's not used in active development now.
